# -*- coding: utf-8 -*-
"""JOGO PAR OU IMPAR

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/MOREIRALT/0671f8b90fed6f1b94a3a430ed5df78c/ol-este-o-colaboratory.ipynb

**JOGO DE IMPAR OU PAR**

1*Quem serão os jogadores
2*Quem escolhe primeiro
3*Quem e impar ou Par
4*Coletar número escolhidos pelos jogadores
5*Calcula se a soma dos números e Impar ou Par
6*Informe quem ganhou.
"""

jogador1 = input('-> Digite o nome do jogador 1:')
jogador2 = input('-> Digite o nome do jogador 2:')
print('------------------------------------------------')
print(f'//{jogador1} Vs {jogador2}//')
print('------------------------------------------------')
primeiro_jogador = input(f'-> Digite 1 para escolher {jogador1} ou 2 para escolher {jogador2}.')
segundo_jogador = None

if primeiro_jogador == '1':
  primeiro_jogador = jogador1
  segundo_jogador = jogador2
elif primeiro_jogador == '2':
  primeiro_jogador = jogador2
  segundo_jogador = jogador1
print('------------------------------------------------')
print(f'//Escolha 0 Para  escolher Impar e 1 Para escolher Par//')
escolha = input(f'-->{jogador1} Você escolhe Impar ou Par?')
escolha2 = None
print('------------------------------------------------')
if escolha == 'Impar' or escolha == 'impar' or escolha == '0':
  escolha = 'Impar'
  escolha2 = 'Par'
elif escolha == 'Par' or escolha == '1':
  escolha = 'Par'
  escolha2 = 'Impar'
print(f'//{segundo_jogador}, você ficou com a {escolha2} e o {primeiro_jogador} ficou com {escolha}')
print('------------------------------------------------')
numero1 = int(input(f'-> {primeiro_jogador} , escolha um numero:'))
numero2 = int(input(f'->{segundo_jogador} , escolha um numero:'))

soma = numero1 + numero2

if soma % 2 == 0:
  vencedor = 'Impar'
else:
  vencedor = 'Par'
if vencedor == escolha:
  print(f'//{segundo_jogador}, Ganhou.//')
else:
  print(f'//{primeiro_jogador}, Ganhou.//')

